### ISSUE TITLE
PECmd (net6): System.PlatformNotSupportedException: System.Drawing.Common is not supported on this platform.

### ISSUE THREAD

**Issue by timtaylor3** [EricZimmerman/Issues#178]
**Only occurs when using --html option.**  

```
Error exporting data: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on this platform.
   at System.Drawing.Image..ctor()
   at System.Drawing.Bitmap..ctor(Stream stream)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.RuntimeResourceSet.ReadValue(DeserializingResourceReader reader, Int32 dataPos, Boolean isString, ResourceLocator& locator)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture)
   at PECmd.Properties.Resources.get_directories()
   at PECmd.Program.DoWork(String f, String d, String k, String o, Boolean q, String json, String jsonf, String csv, String csvf, String html, String dt, Boolean mp, Boolean vss, Boolean dedupe, Boolean debug, Boolean trace)
```

**Comment by EricZimmerman** [comment]
ah yes, all the net drawing stuff relies on GDI.

i will base64 encode the images and store them that way, then just unbase64 and write them out as needed. good find

**Comment by EricZimmerman** [comment]
what version are you using? i have a test already to essentially exit when running PECmd on a non-windows box:

Non-Windows platforms not supported due to the need to load decompression specific Windows libraries! Exiting...

for this reason (needing to decompress pf files), PECmd is windows only.

i suppose i can do a check in case you are not dealing with a windows 10/11 prefetch file tho.

Are you trying to parse a windows 1x file?

**Comment by EricZimmerman** [comment]
![image](https://user-images.githubusercontent.com/4265254/151587174-d25ab61a-b88d-41d9-bfde-a78f7f415319.png)

i uploaded a new build to make sure its current. can you redownload and try it?

**Comment by EricZimmerman** [comment]
i should also say i have and continue to look for a way to do the decompressing on non-Windows platforms, but so far, i havent been able to find a way

**Comment by timtaylor3** [comment]
That worked just fine.  Thanks for the quick turn around.  I am looking forward to be able to your tools on Linux.  :).
