### ISSUE TITLE
RLA is ignoring the --out switch

### ISSUE THREAD

**Issue by 0CM** [EricZimmerman/Issues#217]
RLA is ignoring the —out switch and is trying to update the original registry hives, which will fail when run agains data from read-only image / mount point.

_dotnet —version 6.0.130
Architecture: AARCH64
OS: Ubuntu 24.04_

**HIVES in R/O folder.**

ubuntu@lab00:~/tools/EZTools/rla$ ./rla -d $HOME/DATA/evidence/Windows/System32/config/ --ca --out $HOME/DATA/export/

rla version 2.0.0.0

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/RECmd

Note: Enclose all strings containing spaces with double quotes

Command line: -d /home/ubuntu/DATA/evidence/Windows/System32/config/ --ca --out /home/ubuntu/DATA/export/

Processing hive /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM
Two transaction logs found. Determining primary log...
Primary log: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM.LOG2, secondary log: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM.LOG1
Replaying log file: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM.LOG2
Replaying log file: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM.LOG1
At least one transaction log was applied. Sequence numbers have been updated to 0x1626. New Checksum: 0xCD57A23B
	File /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM exists! Saving as non-compressed name: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM
	Saving updated hive to /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM
There was an error: Read-only file system : '/home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM'
System.IO.IOException: Read-only file system : '/home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at rla.Program.DoWork(String f, String d, String out, Boolean ca, Boolean cn, Boolean debug, Boolean trace) in /home/ubuntu/EZBuild/RECmd/rla/Program.cs:line 127

**HIVES in R/W directory.** 

./rla -d $HOME/DATA/export/dirtyreg/ --ca --out $HOME/DATA/export/

rla version 2.0.0.0

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/RECmd

Note: Enclose all strings containing spaces with double quotes

Command line: -d /home/ubuntu/DATA/export/dirtyreg/ --ca --out /home/ubuntu/DATA/export/

Processing hive /home/ubuntu/DATA/export/dirtyreg/SYSTEM
	Hive /home/ubuntu/DATA/export/dirtyreg/SYSTEM is not dirty, but --ca is True. Copying...
	File /home/ubuntu/DATA/export/dirtyreg/SYSTEM exists! Saving as non-compressed name: /home/ubuntu/DATA/export/dirtyreg/SYSTEM
	Saving updated hive to /home/ubuntu/DATA/export/dirtyreg/SYSTEM

**Debug**

./rla -d $HOME/DATA/evidence/Windows/System32/config/ --debug --out $HOME/DATA/export/

[17:24:20.656 INF] rla version 2.0.0.0

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/RECmd

Note: Enclose all strings containing spaces with double quotes

[17:24:20.669 INF] Command line: -d /home/ubuntu/DATA/evidence/Windows/System32/config/ --debug --out /home/ubuntu/DATA/export/

[17:24:20.740 INF] Processing hive /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM
[17:24:20.872 DBG] Got hive header. Embedded file name SYSTEM. Base Name system
[17:24:20.942 DBG] Got transaction log header. Embedded file name SYSTEM. Base Name system
[17:24:20.945 DBG] Got transaction log header. Embedded file name SYSTEM. Base Name system
[17:24:20.945 INF] Two transaction logs found. Determining primary log...
[17:24:20.946 INF] Primary log: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM.LOG2, secondary log: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM.LOG1
[17:24:20.946 INF] Replaying log file: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM.LOG2
[17:24:20.947 INF] Replaying log file: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM.LOG1
[17:24:20.949 INF] At least one transaction log was applied. Sequence numbers have been updated to 0x1626. New Checksum: 0xCD57A23B
[17:24:20.950 WRN] 	File /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM exists! Saving as non-compressed name: /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM
[17:24:20.950 INF] 	Saving updated hive to /home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM
[17:24:20.951 ERR] There was an error: Read-only file system : '/home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM'
System.IO.IOException: Read-only file system : '/home/ubuntu/DATA/evidence/Windows/System32/config/SYSTEM'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at rla.Program.DoWork(String f, String d, String out, Boolean ca, Boolean cn, Boolean debug, Boolean trace) in /home/ubuntu/EZBuild/RECmd/rla/Program.cs:line 127

**Comment by EricZimmerman** [comment]
fixed and updated

Command line: -d /mnt/c/temp/dirty --out /mnt/c/temp/clean/

        Hives found: 2

Processing hive /mnt/c/temp/dirty/Amcache.hve
Two transaction logs found. Determining primary log...
Primary log: /mnt/c/temp/dirty/Amcache.hve.LOG1, secondary log: /mnt/c/temp/dirty/Amcache.hve.LOG2
Replaying log file: /mnt/c/temp/dirty/Amcache.hve.LOG1
Replaying log file: /mnt/c/temp/dirty/Amcache.hve.LOG2
At least one transaction log was applied. Sequence numbers have been updated to 0x05E5. New Checksum: 0xEDB3DC43
        Saving updated hive to /mnt/c/temp/clean/_mnt_c_temp_dirty_Amcache.hve

Processing hive /mnt/c/temp/dirty/SYSTEM
Two transaction logs found. Determining primary log...
Primary log: /mnt/c/temp/dirty/SYSTEM.LOG1, secondary log: /mnt/c/temp/dirty/SYSTEM.LOG2
Replaying log file: /mnt/c/temp/dirty/SYSTEM.LOG1
Replaying log file: /mnt/c/temp/dirty/SYSTEM.LOG2
At least one transaction log was applied. Sequence numbers have been updated to 0xDD6E. New Checksum: 0x6F930CAB
        Saving updated hive to /mnt/c/temp/clean/_mnt_c_temp_dirty_SYSTEM

Total processing time: 0.198 seconds

eric@ERZDev:/mnt/d/Code/RECmd/rla/bin/Debug/net6.0$ dotnet rla.dll -d  /mnt/c/temp/dirty --out /mnt/c/temp/clean/ --nop

rla version 2.0.0.0

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/RECmd

Note: Enclose all strings containing spaces with double quotes

Command line: -d /mnt/c/temp/dirty --out /mnt/c/temp/clean/ --nop

        Hives found: 2

Processing hive /mnt/c/temp/dirty/Amcache.hve
Two transaction logs found. Determining primary log...
Primary log: /mnt/c/temp/dirty/Amcache.hve.LOG1, secondary log: /mnt/c/temp/dirty/Amcache.hve.LOG2
Replaying log file: /mnt/c/temp/dirty/Amcache.hve.LOG1
Replaying log file: /mnt/c/temp/dirty/Amcache.hve.LOG2
At least one transaction log was applied. Sequence numbers have been updated to 0x05E5. New Checksum: 0xEDB3DC43
        Saving updated hive to /mnt/c/temp/clean/Amcache.hve

Processing hive /mnt/c/temp/dirty/SYSTEM
Two transaction logs found. Determining primary log...
Primary log: /mnt/c/temp/dirty/SYSTEM.LOG1, secondary log: /mnt/c/temp/dirty/SYSTEM.LOG2
Replaying log file: /mnt/c/temp/dirty/SYSTEM.LOG1
Replaying log file: /mnt/c/temp/dirty/SYSTEM.LOG2
At least one transaction log was applied. Sequence numbers have been updated to 0xDD6E. New Checksum: 0x6F930CAB
        Saving updated hive to /mnt/c/temp/clean/SYSTEM

Total processing time: 0.200 seconds

**Comment by 0CM** [comment]
Briliant, thank you!
